### ISSUE TITLE
[ CLIENT ] Comprar featrue

### ISSUE THREAD

**Issue by elena20ruiz** [carlotacb/compra-local#22]
**Pages**
 - [x] Search shop page
- [x] Store page

**TODO Features:**
- [x] _SEARCH_ Create functions for `onClick` filter buttons
- [ ] _SEARCH_ Create function for `onChange` input for search shops
- [x] _STORE_ Show store information programatically
